name: Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      # actions/setup-python@v6.2.0
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.14"

      - name: Install Python dependencies from requirements-doc.txt
        run: pip install -r doc/requirements-doc.txt

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y
        shell: bash

      - name: Build documentation
        run: sphinx-build doc _build

      - name: Set CNAME if in public repo
        id: cname
        run: |
          if [ "${{ github.repository }}" = "erbsland-dev/erbsland-unittest" ]; then
            echo "CNAME=unittest.erbsland.dev" >> $GITHUB_ENV
          fi

      - name: Deploy
        # peaceiris/actions-gh-pages@v4.0.0
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
          cname: ${{ env.CNAME }}
